### ISSUE TITLE
BK8000L does not communicate

### ISSUE THREAD

**Issue by Apodasch** [tomaskovacik/BK8000L#12]
Hello,
First of all I would like to thank you, you created nice and easy to use library for BK8000L, but still, I am probably doing something wrong...
I use ESP8622 to communicate with BK8000L because both chips are operating in 3.3V. Unfortunately your example code does not work for me.
After start it returns this to the console:
15:47:15.191 -> ⸮O⸮$<⸮H⸮⸮D>⸮,4⸮⸮press h for help
15:47:17.552 -> Bluetooth disconnected
15:47:17.552 -> Music stoped
15:47:17.592 -> Module OFF

And the only command that is "working" (I mean I get a response, because it actually does nothing with the module) is command 1 (enter pairing).

15:55:44.709 -> Bluetooth in pairing mode

But if I use any other commands, I get no response :(

In your code I only changed the swSerial pins (#16) and I add LED indication (#51 and #356) so that I know if the esp received the commend from PC.

The BK8000L is working (I tested the music playback and so on), but only the communication, the main reason why I bought it, is not working.

Please can you help me? I would be very thankful,  master.

My code:
[new_test_BT.zip](https://github.com/tomaskovacik/BK8000L/files/5012251/new_test_BT.zip)

My wiring:
![IMG_20200802_160406](https://user-images.githubusercontent.com/69112899/89124786-f87aa380-d4d9-11ea-9fd2-0230d70f9be7.jpg)
![IMG_20200802_160320](https://user-images.githubusercontent.com/69112899/89124811-1b0cbc80-d4da-11ea-81e6-0a95b4cde858.jpg)
![IMG_20200802_160339](https://user-images.githubusercontent.com/69112899/89124830-3677c780-d4da-11ea-9ebe-15162ff5e793.jpg)
![IMG_20200802_160253](https://user-images.githubusercontent.com/69112899/89124838-455e7a00-d4da-11ea-943b-9ea754208719.jpg)

**Comment by tomaskovacik** [comment]
Try simply forward serial vomunication to computer if module actualy send something. But in most cases uart is not enabled on your module.On 2 Aug 2020 16:10, Apodasch <notifications@github.com> wrote:

Hello,

First of all I would like to thank you, you created nice and easy to use library for BK8000L, but still, I am probably doing something wrong...

I use ESP8622 to communicate with BK8000L because both chips are operating in 3.3V. Unfortunately your example code does not work for me.

After start it returns this to the console:

15:47:15.191 -> ⸮�O⸮$<⸮H⸮⸮D>⸮,4⸮⸮press h for help

15:47:17.552 -> Bluetooth disconnected

15:47:17.552 -> Music stoped

15:47:17.592 -> Module OFF

And the only command that is "working" (I mean I get a response, because it actually does nothing with the module) is command 1 (enter pairing).

15:55:44.709 -> Bluetooth in pairing mode

But if I use any other commands, I get no response :(

In your code I only changed the swSerial pins (#16) and I add LED indication (#51 and #356) so that I know if the esp received the commend from PC.

The BK8000L is working (I tested the music playback and so on), but only the communication, the main reason why I bought it, is not working.

Please can you help me? I would be very thankful,  master.

My code:

new_test_BT.zip

My wiring:

**Comment by Apodasch** [comment]
Ok, thank you for quick response.
Do you know how to enable uart on BK8000L? And Why it reacts to command "1" and its reply seems to be correct - it replies "Bluetooth is in paring mode."

**Comment by Apodasch** [comment]
Example:

..........
16:28:38.670 -> getName                      s
16:28:38.670 -> getConnectioStatus           t
16:28:38.670 -> getPinCode                   u
16:28:38.670 -> getAddress                   v
16:28:38.670 -> getSoftwareVersion           w
16:28:38.670 -> MusicGetStatus               x
16:28:38.670 -> getHFPstatus                 y
16:28:38.670 -> StartModule                  z
16:28:38.670 -> send APT data            A+data
16:28:38.670 -> APT login          B
16:28:38.772 -> Command: h
16:28:38.772 -> Done! Waiting for new command...
16:28:44.395 -> Command: 2
16:28:44.395 -> Done! Waiting for new command...
16:28:47.804 -> Command: 3
16:28:47.804 -> Done! Waiting for new command...
16:28:50.002 -> Command: 5
16:28:50.002 -> Done! Waiting for new command...
16:28:53.005 -> Command: 4
16:28:53.005 -> Done! Waiting for new command...
16:29:04.224 -> Command: 1
16:29:04.224 -> Done! Waiting for new command...
16:29:04.444 -> **Bluetooth in pairing mode**

**Comment by tomaskovacik** [comment]
It is probably bug

**Comment by tomaskovacik** [comment]
Follow this how to

https://kovo-blog.blogspot.com/2017/11/bk8000l-change-name.html

and use this bin file:

https://github.com/tomaskovacik/kicad-library/blob/master/library/datasheet/F-6188_BK8000L/bins/firmware_serial.bin

**Comment by Apodasch** [comment]
Thanks a lot!
I followed all the instructions and I have succesfully flashed the module and also changed it's name.
It is working nearly perfectly now. 
The only thing that is not working is pairing detection or pairing state change.
I would like to prevent the module to be in a paring mode while it is disconnected, until some button/switch is pressed (so that no strangers can connect, only a person who has already paired last time, or you have to push a button to re-pair).

Please check this code:

void loop(){
  
  //should be call periodically, to get notifications from module, for example if someone calling...
  BT.getNextEventFromBT();
  
  if (BTState != BT.BTState) {
    BTState = BT.BTState;
    switch (BT.BTState) {
      case BT.Connected:
        Serial.println(F("Bluetooth connected"));
        break;
      case BT.Disconnected:
        Serial.println(F("Bluetooth disconnected"));
        BT.pairingExit();
        break;
      case BT.Pairing:
        Serial.println("BT is in pairing mode! Exitting pairing mode...");
        BT.pairingExit();
        break;
    }
  }

  if (BTState != BT.Connected and !(digitalRead(some_switch))) {
    BT.pairingExit();
  }
  
}

It seems to me that the BT.pairingExit() function (command) does nothing, because the module stays in the paring mode while it is disconnected.

Do you have any idea how to prepare tihs functionality?

Thank you very much once more!

Bye
Adam

**Comment by tomaskovacik** [comment]
Please check if module behave as you expected using only AT commands from datasheet, if yes then there is problem in library. If not , then I can not fox it unfortunetly. I am for next working week away from my gear, so no chance that i will test this right now.T.On 2 Aug 2020 21:12, Apodasch <notifications@github.com> wrote:
Thanks a lot!
I followed all the instructions and I have succesfully flashed the module and also changed it's name.
It is working nearly perfectly now.
The only thing that is not working is pairing detection or pairing state change.
I would like to prevent the module to be in a paring mode while it is disconnected, until some button/switch is pressed (so that no strangers can connect, only a person who has already paired last time, or you have to push a button to re-pair).
Please check this code:
void loop(){
//should be call periodically, to get notifications from module, for example if someone calling...
BT.getNextEventFromBT();
if (BTState != BT.BTState) {
BTState = BT.BTState;
switch (BT.BTState) {
case BT.Connected:
Serial.println(F("Bluetooth connected"));
break;
case BT.Disconnected:
Serial.println(F("Bluetooth disconnected"));
BT.pairingExit();
break;
case BT.Pairing:
Serial.println("BT is in pairing mode! Exitting pairing mode...");
BT.pairingExit();
break;
}
}
if (BTState != BT.Connected and !(digitalRead(some_switch))) {
BT.pairingExit();
}
}
It seems to me that the BT.pairingExit() function (command) does nothing, because the module stays in the paring mode while it is disconnected.
Do you have any idea how to prepare tihs functionality?
Thank you very much once more!
Bye
Adam

**Comment by Apodasch** [comment]
You already helped a lot. No problem.
Or if you have another idea how to secure the bt receiver somehow? Did you already did some project where you have implemented this? Are there any other usefull tools for flashing or customizing the BK8000L? If something comes to your mind, just leave me a comment here.
Thank you once more.
Adam

**Comment by tomaskovacik** [comment]
Pull reset to ground noone will connectT.On 2 Aug 2020 22:15, Apodasch <notifications@github.com> wrote:
You already helped a lot. No problem.
Or if you have another idea how to secure the bt receiver somehow? Did you already did some project where you have implemented this? Are there any other usefull tools for flashing or customizing the BK8000L? If something comes to your mind, just leave me a comment here.
Thank you once more.
Adam

**Comment by Apodasch** [comment]
Hi,
that is not actually what I need. If I pull reset to ground, module resets and I suppose stays in preboot state until reset is released.

Imagine my situation:
I would like to use this module for my home stereo speakers. I would like to connect my personal mobile phone so that I can play music. When I leave home i do not power off my home speakers and I do not want to power off the bluetooth module too. If my mobile disconnects, the module goes to pairing mode and anybody else can connect (neighbors) while I am not home. I wish that the module stay in diconnected state but **not come to pairing mode automatically.**
Then, if you come back from work you can simply reconnect with your personal mobile, because the module is still on, diconnected and you are already paired and you do not need to repair and you simply connect - no need to press any button or to power on the module again when already paired device try to connect - that is why the reset solution is not suitable for me.
Paring should only be possible when some button is pressed or something like this.

As I already said I am using ESP8266 (Wemos D1) as controller - will communicate with BT module, and possibly handle pairing button.

Any idea now?
Thank you

Adam

**Comment by tomaskovacik** [comment]
ok, that situation is totally different from the one you previously mentioned:

"I would like to prevent the module to be in a paring mode while it is disconnected, until some button/switch is pressed (so that no strangers can connect, only a person who has already paired last time, or you have to push a button to re-pair)." :+1: 

in this case, try to investigate if AT+CB make module undiscoverable. if not, then there is probably nothing we can do.

but you can try to investigate if the configuration of bk8000l chip can be changed, take look at this thread on google groups: https://groups.google.com/forum/#!topic/bk8000l/1WuboNBVpnY

t.

**Comment by Apodasch** [comment]
Hello, I did some more investigation and I came to at least some solution.
First of all I found very useful information on [the site you have provided](https://groups.google.com/g/bk8000l). Thank you very much for that.
Next thing is that AT command AT+CB either does not work at all, or it works, but the module itself switches back to pairing immediately after exitting pairing, when there is no device connected. So, not useful for me...
I checked the configuration and I tried to reconfigure the module, but I did not find any configuration bit to prevent the module from entering pairing mode automatically.
I found a workaround which is somehow working (better than nothing).
After that the module starts, I use BT.connectLastDevice() every 500ms to force the module to connect to the last device. Even if last connected device is not reachable and it fails, it results in ignoring incomming pairing request. The only problem I found is that after some time of this AT command attack to the module, the module gets frozen and you can not communicate anymore and you cannot even connect with bt client. To avoid this I reboot the BT module with its reset pin every 5 minutes while in disconnect mode. If I wish to pair with another device I switch to pairing mode with BT.pairingInit(); which works fine.
It is not the best solution, but it is a solution that meets the expected behavior from the user.

Thank you very much for all the help.
I think we can close the issue.

Farewell
Adam

**Comment by tomaskovacik** [comment]
A preco sme si pisali po anglicky? :D zatvaram

**Comment by Apodasch** [comment]
Jo,
zkoumal jsem tvoje jméno a později mi docvaklo, že by si mohl být Slovák.
Nevadí aspoň si z toho něco vezmou taky zahraniční bastlíři, kteří se
dostanou do pasti stejně jako já.

Jinak díky a měj se hezky.

Adam

Dne pá 7. 8. 2020 9:00 uživatel Tomáš Kováčik <notifications@github.com>
napsal:
