### ISSUE TITLE
Possible to control EQ?

### ISSUE THREAD

**Issue by johnyradio** [tomaskovacik/BK8000L#5]
hi

can this lib be used to control the chip's EQ?

thx!

**Comment by tomaskovacik** [comment]
hello, 

NOT, maybe in future it will be, it depend.

while I was translating SW for beken chips, this one come out with something which can help you.
In software is tab name "Audio equlization" (it actualy google translate for some china text) so take a look and give it a try

here is link to SW:
https://github.com/tomaskovacik/kicad-library/raw/master/library/datasheet/F-6888_bk3254/BEKEN_JTAG_bk3254/3254_ToolKit2.6.exe

you need to connet module over some usb to serial converter, I suse cp2102 base 1$ module, 3V3 connected to battery pin, ground to ground ant TX to RX and RX to TX at module. 

if you manage to make it pleasy drop me message here with log from SW and some typing what is what, i can then implement it in library.

thx!

**Comment by johnyradio** [comment]
Thx! Will let you know if I have progress.

**Comment by xandeerzz** [comment]
Does that program really work?  The BK8000L might have the same MCU core as BK3254. I also found a string in the flash dump which suggested that.
Can't wait to get my module and mod it if the software works :)

**Comment by tomaskovacik** [comment]
I really did not know, for me it did not do anything for bk8000 OR 3254 modules :/  but as always, maybe set it wrong ... or it need to be enabled, probably best shot is write to chines supplier about this ..

**Comment by johnyradio** [comment]
Thx for info!
I'm still learning.

**Comment by xandeerzz** [comment]
I hooked up a virtual com port bridge to see what it does at the output when using some settings. I found that you can do some other stuff using AT commands. You can, for example, set the EQ gain for each frequency or modify DAC gain or MIC gain, change noise suppresion levels, change mic bias voltage and so on. Also, I did an analysis of the binary output data, and the first chunk of data seems to correlate to the BK8000L. I'll try to flash that image over to the BK8000L and see if it does anything. But at the moment I don't have the module on hand, so it's up to the w/end or next week. I'll keep you updated :)

**Comment by tomaskovacik** [comment]
Check issue #6 , there are all commands  which i found

**Comment by johnyradio** [comment]
Many thanks!

**Comment by johnyradio** [comment]
I'm trying the CSR8645. Seems better supported.

Can even connect yet. Unsure which is correct power pin.

See my comment here at bottom
https://www.instructables.com/id/CSR-Bluetooth-Module-Programming/

**Comment by johnyradio** [comment]
@xandeerzz Have you had some progress? 

I'm trying to find a bluetooth chip with equalizer. The only ones i found so far are the BK8000L and the CSR8645.  I was never able to access equalizer settings on the CSR chip. Do you know of any others?

thx

**Comment by tomaskovacik** [comment]
check BM20 from microchip it is more $ but nothing horrible, 8euros

https://www.microchip.com/wwwproducts/en/BM20

**Comment by johnyradio** [comment]
Many thanks, Thomas.
Why not use the BK8000L?

**Comment by tomaskovacik** [comment]
For me, setting eq on bk8000l never works

**Comment by johnyradio** [comment]
Thx for the recommendation.
Can you set EQ on CSR chip?

**Comment by johnyradio** [comment]
actually more than i can spend. Need about $5 for the whole module.

**Comment by alexzirnea** [comment]
> @xandeerzz Have you had some progress?
> 
> I'm trying to find a bluetooth chip with equalizer. The only ones i found so far are the BK8000L and the CSR8645. I was never able to access equalizer settings on the CSR chip. Do you know of any others?
> 
> thx

It did work on mine, I was able to boost the low frequencies a bit, but the changes you'll make must be subtle, otherwise it will start to clip and sound horrible. 
I don't really recall how I did it, but all in all you have to use the BK3254 config tool and start from there. You must have the UART-enabled firmware. Also, I believe you can enable UART on any firmware by changing a specific byte in the firmware. Just Use the tool and generate one firmware, change what parameters you like one by one, and compare the two, you'll figure out pretty soon what the deal is. It is a bit disappointing that we don't have any documentation whatsoever except some random briefs from chinese sites.

**Comment by johnyradio** [comment]
alexzirnea wrote:
you have to use the BK3254 config tool

Thanks for the info! i assume that's for the BK8000L, correct? Were you able to set EQ on the CSR module?

alexzirnea wrote:
changes you'll make must be subtle, otherwise it will start to clip and sound horrible.

But you can reduce the input level to compensate, correct?

thx

**Comment by alexzirnea** [comment]
Yep, the BK3254 tool works for BK8000L. The flash memory mapping is different, but the overall architecture seems to be the same, and possibly the same core(from which I recall is the infamous 8051 with some proprietary extensions). BK8000L is a stripped-down version of the BK3254 if I remember correctly

I have never used the CSR module

You have a few EQ bands and you can also choose the filter type, and you can reduce the overall gain of all bands, so that should be fine

**Comment by johnyradio** [comment]
can you set EQ on the CSR using the PS Tool?
i could not connect with Blue Suite, but i CAN connect with PS Tool.
